/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salones.vista;

import javax.swing.table.DefaultTableModel;
import Salones.controlador.UsuarioControlador;
import Salones.modelo.Usuario;
import Salones.datos.J_Conector;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author u-jona
 */
public class FrmControlUsuario extends javax.swing.JFrame {
  ArrayList<String> claves = new ArrayList<String>();
    /**
     * Creates new form FrmControlUsuario
     */
    public FrmControlUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCUInsertar = new javax.swing.JButton();
        btnCUEliminar = new javax.swing.JButton();
        btnCUModificar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCUUsuarios = new javax.swing.JTable();
        btnCUAceptar = new javax.swing.JButton();
        btnCUCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Control Usuarios");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCUInsertar.setText("Insertar");
        btnCUInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUInsertarActionPerformed(evt);
            }
        });

        btnCUEliminar.setText("Eliminar");
        btnCUEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUEliminarActionPerformed(evt);
            }
        });

        btnCUModificar.setText("Modificar");
        btnCUModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUModificarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCUInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCUModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCUEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCUInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCUModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCUEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCUUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCUUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCUUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCUUsuarios);

        btnCUAceptar.setText("Aceptar");
        btnCUAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUAceptarActionPerformed(evt);
            }
        });

        btnCUCancelar.setText("Cancelar");
        btnCUCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCUAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCUCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCUAceptar)
                            .addComponent(btnCUCancelar)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCUInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUInsertarActionPerformed
        // TODO add your handling code here:
        FrmControlUsuarioInsertar fcui = new FrmControlUsuarioInsertar();
        fcui.setVisible(true);

    }//GEN-LAST:event_btnCUInsertarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:  
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //this.refrescar();
        this.mostrar();

    }//GEN-LAST:event_formWindowOpened

    private void btnCUEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUEliminarActionPerformed
        // TODO add your handling code here:
        UsuarioControlador eli = new UsuarioControlador();
        Usuario u = new Usuario();
        try {
        int fila = tblCUUsuarios.getSelectedRow();
        String codigo = tblCUUsuarios.getValueAt(fila, 0).toString();
        u.setCodigo(Integer.parseInt(codigo));
        
        if(JOptionPane.showConfirmDialog(null, "Seguro que desea Eliminar")== JOptionPane.YES_NO_OPTION){
            eli.eliminarUsuario(u);
        }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado usuario a eliminar, debe de seleccionar un usuario para continuar");
        }
        this.mostrar();


    }//GEN-LAST:event_btnCUEliminarActionPerformed

    private void tblCUUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCUUsuariosMouseClicked
        // TODO add your handling code here:
//        J_Conector con = new J_Conector();
//        con.conectar();
//        int fila = tblCUUsuarios.getSelectedRow();
//        String codigo = tblCUUsuarios.getValueAt(fila, 0).toString();
//        String nombre = tblCUUsuarios.getValueAt(fila, 1).toString();
//        String usuario = tblCUUsuarios.getValueAt(fila, 2).toString();
//        //String password = tblCUUsuarios.getValueAt(fila, 3).toString();
//        String password = claves.get(fila);
//        //int estado = (int) tblCUUsuarios.getValueAt(fila, 3);
//        FrmControlUsuarioModificar mo = new FrmControlUsuarioModificar();
//        mo.setCodigo(codigo);
//        mo.setNombre(nombre);
//        mo.setUsuario(usuario);
//        mo.setPass(password);
//        //mo.setEstado(estado);
//        if (evt.getClickCount() == 2) {
//            mo.setVisible(true);
//        }

    }//GEN-LAST:event_tblCUUsuariosMouseClicked

    private void btnCUModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUModificarActionPerformed
        // TODO add your handling code here:
         J_Conector con = new J_Conector();
        con.conectar();
        try {
        int fila = tblCUUsuarios.getSelectedRow();
        String codigo = tblCUUsuarios.getValueAt(fila, 0).toString();
        String nombre = tblCUUsuarios.getValueAt(fila, 1).toString();
        String usuario = tblCUUsuarios.getValueAt(fila, 2).toString();
        //String password = tblCUUsuarios.getValueAt(fila, 3).toString();
        String password = claves.get(fila);
        //int estado = (int) tblCUUsuarios.getValueAt(fila, 3);
        FrmControlUsuarioModificar mo = new FrmControlUsuarioModificar();
        mo.setCodigo(codigo);
        mo.setNombre(nombre);
        mo.setUsuario(usuario);
        mo.setPass(password);
        mo.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado usuario a modificar, debe seleccionar un usuario antes de continuar");
        }
       
    }//GEN-LAST:event_btnCUModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        this.mostrar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCUCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCUCancelarActionPerformed

    private void btnCUAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUAceptarActionPerformed
        // TODO add your handling code here:
        this.mostrar();
        dispose();
    }//GEN-LAST:event_btnCUAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmControlUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmControlUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmControlUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmControlUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmControlUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCUAceptar;
    private javax.swing.JButton btnCUCancelar;
    private javax.swing.JButton btnCUEliminar;
    private javax.swing.JButton btnCUInsertar;
    private javax.swing.JButton btnCUModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCUUsuarios;
    // End of variables declaration//GEN-END:variables
    protected void mostrar() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.setColumnCount(0);
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Usuario");
        //modelo.addColumn("Pass");
        //modelo.addColumn("Estado de Usuario");
        UsuarioControlador uc = new UsuarioControlador();
        for (Usuario cu : uc.consultarUsuario()) {
            //utilizar para llamar cada array a mostrar
            modelo.addRow(new Object[]{cu.getCodigo(),cu.getNombre(), cu.getUsuario(), claves.add(cu.getPassword())});
            //claves.add(cu.getPassword());
        }
        tblCUUsuarios.setModel(modelo);
    }

    protected void eliminar() {

    }

}
